
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Ishaan
 */
public class AITTT extends javax.swing.JFrame
{

    /**
     * Creates new form AITTT
     */
    public AITTT()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        oo = new javax.swing.JButton();
        ol = new javax.swing.JButton();
        ot = new javax.swing.JButton();
        lo = new javax.swing.JButton();
        ll = new javax.swing.JButton();
        lt = new javax.swing.JButton();
        to = new javax.swing.JButton();
        tl = new javax.swing.JButton();
        tt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setIconImages(null);
        setPreferredSize(new java.awt.Dimension(200, 200));
        setSize(new java.awt.Dimension(182, 200));

        oo.setText("?");
        oo.setFocusPainted(false);
        oo.setMinimumSize(new java.awt.Dimension(50, 50));
        oo.setPreferredSize(new java.awt.Dimension(50, 50));
        oo.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                ooActionPerformed(evt);
            }
        });

        ol.setText("?");
        ol.setPreferredSize(new java.awt.Dimension(50, 50));
        ol.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                olActionPerformed(evt);
            }
        });

        ot.setText("?");
        ot.setPreferredSize(new java.awt.Dimension(50, 50));
        ot.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                otActionPerformed(evt);
            }
        });

        lo.setText("?");
        lo.setPreferredSize(new java.awt.Dimension(50, 50));
        lo.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                loActionPerformed(evt);
            }
        });

        ll.setText("?");
        ll.setPreferredSize(new java.awt.Dimension(50, 50));
        ll.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                llActionPerformed(evt);
            }
        });

        lt.setText("?");
        lt.setPreferredSize(new java.awt.Dimension(50, 50));
        lt.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                ltActionPerformed(evt);
            }
        });

        to.setText("?");
        to.setPreferredSize(new java.awt.Dimension(50, 50));
        to.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                toActionPerformed(evt);
            }
        });

        tl.setText("?");
        tl.setPreferredSize(new java.awt.Dimension(50, 50));
        tl.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                tlActionPerformed(evt);
            }
        });

        tt.setText("?");
        tt.setPreferredSize(new java.awt.Dimension(50, 50));
        tt.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                ttActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(to, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(oo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ol, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tl, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(oo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(to, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ooActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_ooActionPerformed
    {//GEN-HEADEREND:event_ooActionPerformed
        action(new Location(0, 0));
    }//GEN-LAST:event_ooActionPerformed

    private void olActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_olActionPerformed
    {//GEN-HEADEREND:event_olActionPerformed
        action(new Location(0, 1));
    }//GEN-LAST:event_olActionPerformed

    private void otActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_otActionPerformed
    {//GEN-HEADEREND:event_otActionPerformed
        action(new Location(0, 2));
    }//GEN-LAST:event_otActionPerformed

    private void loActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_loActionPerformed
    {//GEN-HEADEREND:event_loActionPerformed
        action(new Location(1, 0));
    }//GEN-LAST:event_loActionPerformed

    private void llActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_llActionPerformed
    {//GEN-HEADEREND:event_llActionPerformed
        action(new Location(1, 1));
    }//GEN-LAST:event_llActionPerformed

    private void ltActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_ltActionPerformed
    {//GEN-HEADEREND:event_ltActionPerformed
        action(new Location(1, 2));
    }//GEN-LAST:event_ltActionPerformed

    private void toActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_toActionPerformed
    {//GEN-HEADEREND:event_toActionPerformed
        action(new Location(2, 0));
    }//GEN-LAST:event_toActionPerformed

    private void tlActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_tlActionPerformed
    {//GEN-HEADEREND:event_tlActionPerformed
        action(new Location(2, 1));
    }//GEN-LAST:event_tlActionPerformed

    private void ttActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_ttActionPerformed
    {//GEN-HEADEREND:event_ttActionPerformed
        action(new Location(2, 2));
    }//GEN-LAST:event_ttActionPerformed

    public Board b = new Board();

    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(AITTT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(AITTT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(AITTT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(AITTT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new AITTT().setVisible(true);
            }
        });

//            int res = JOptionPane.showConfirmDialog(null, "Should The Computer Go First?", "", JOptionPane.YES_NO_OPTION);
//
//            if (res == JOptionPane.YES_OPTION)
//            {
//                Location loc = new Location((int) (Math.random() * 3), (int) (Math.random() * 3));
//                b.makeMove(loc, Board.AI);
//                toButton(loc, "O");
//                b.display();
//            }
    }

    private void action(Location loc)
    {
        if (b.makeMove(loc, Board.PLAYER))
            toButton(loc, "X");
        else
            return;

        if (b.isOver())
            end();

        b.minmax(0, Board.AI);
        b.makeMove(Board.AIMove, Board.AI);
        toButton(Board.AIMove, "O");

        if (b.isOver())
            end();

        b.display();
    }

    private void end()
    {
        if (b.hasWon(Board.AI))
            JOptionPane.showMessageDialog(null, "You Lose!");
        else if (b.hasWon(Board.PLAYER))
            JOptionPane.showMessageDialog(null, "You Win!");
        else
            JOptionPane.showMessageDialog(null, "Draw!");
        System.exit(0);
    }

    private void toButton(Location loc, String txt)
    {
        switch (loc.x + "" + loc.y)
        {
            case "00":
                oo.setText(txt);
                break;
            case "01":
                ol.setText(txt);
                break;
            case "02":
                ot.setText(txt);
                break;
            case "10":
                lo.setText(txt);
                break;
            case "11":
                ll.setText(txt);
                break;
            case "12":
                lt.setText(txt);
                break;
            case "20":
                to.setText(txt);
                break;
            case "21":
                tl.setText(txt);
                break;
            case "22":
                tt.setText(txt);
                break;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ll;
    private javax.swing.JButton lo;
    private javax.swing.JButton lt;
    private javax.swing.JButton ol;
    private javax.swing.JButton oo;
    private javax.swing.JButton ot;
    private javax.swing.JButton tl;
    private javax.swing.JButton to;
    private javax.swing.JButton tt;
    // End of variables declaration//GEN-END:variables
}
